language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6


before_install:
  - pip freeze | xargs pip uninstall -y
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"

install:
  - poetry install

script:
  - poetry run flake8 heisenbug tests
  - poetry run mypy heisenbug
  - poetry run pytest
  # The next line will fail to demonstrate how bad our tests actually are:
  - poetry run mutmut run || true
  - poetry check
  - poetry run pip check
  - poetry run safety check --bare --full-report

after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: change
